// <auto-generated />
using BooksSpr2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksSpr2026.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260210072341_addingBooksTableWithSeedData")]
    partial class addingBooksTableWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksSpr2026.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "J.K. Rowling",
                            BookTitle = "Harry Potter and the Prisoner of Azkaban",
                            CategoryId = 2,
                            Description = "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter",
                            ImgUrl = "",
                            Price = 22.91m
                        },
                        new
                        {
                            BookId = 2,
                            Author = "DK Travel",
                            BookTitle = "USA National Parks: Lands of Wonder",
                            CategoryId = 1,
                            Description = "The USA's National Parks truly are blah blah blah.",
                            ImgUrl = "",
                            Price = 16.80m
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Scott Selikoff",
                            BookTitle = "OCP Oracle Certified Professional Java SE 17 Developer Study Guide: Exam 1Z0-829",
                            CategoryId = 3,
                            Description = "In the OCP Oracle Certified Professional etc.",
                            ImgUrl = "",
                            Price = 36.99m
                        });
                });

            modelBuilder.Entity("BooksSpr2026.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Books about going places",
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Books that aren't real",
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "This is the description for the technology category",
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("BooksSpr2026.Models.Book", b =>
                {
                    b.HasOne("BooksSpr2026.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
